### ISSUE TITLE
Logging in as another user is broken on IE and Edge

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1276] opened 2016-05-12 15:35 UTC
In these browsers you're taken to the admin login screen.

**Comment by mworrell** [comment] 2016-05-13 12:22
We change the session cookie when logging in as another person.
Maybe this cookie can't be set properly?

It used to work on older IE browsers.

**Comment by mmzeeman** [comment] 2016-05-13 14:01
Or is this a header order problem? Just like chrome has with redirects and setting cookies?

**Comment by Dirklectisch** [comment] 2016-06-01 13:14
I have been able te reproduce this problem on Windows 10 with IE 11.162.10586. The problem seems to be with the redirect not with the actual authentication. The user switch has been successful but you end up on the wrong page.

**Comment by mworrell** [comment] 2016-06-02 09:46
Can you see what is wrong with the redirect?
Is it missing the hostname or something else?

**Comment by ddeboer** [comment] 2016-07-27 11:59
We’re now also seeing a bug where we’re unable to log in at `/admin` with Edge (with all Ginger modules disabled). Still investigating.

**Comment by Dirklectisch** [comment] 2016-10-13 07:56
@krista-ramakers Could you try again to reproduce this problem, otherwise we can close it of. (see issue of the pivotal tracker JHM 119195247).

**Comment by krista-ramakers** [comment] 2016-10-13 08:18
The redirect to the Ginger /admin log on screen still happens, when you choose to log on as someone who does not have the rights to access admin. If you go to the home page by changing the URL, you're properly logged on as the person you'd want to log on as (both IE11 and Edge).

**Comment by mworrell** [comment] 2016-10-13 08:21
That redirect is a feature. As the system tries to stay on the same page (reloads the page you were on) when changing the user. As the new user is not allowed to see that page, the new user is redirected to the admin log on screen.

**Comment by mworrell** [comment] 2019-08-14 16:06
I assume this issue is fixed?

Closing for now.

**Closed by mworrell** 2019-08-14 16:06 UTC
Labels: defect
