### ISSUE TITLE
Editing multiple languages in Tinymce problem

### ISSUE THREAD

**Issue by michielklonhammer** [zotonic/zotonic#2879] opened 2022-02-11 16:17 UTC
When switching between a first language with some text to the next language, the second language tinymce field is closed. 

The workaround is opening the HTML view and then entering some text.
This is quite hard to reproduce.

I've seen it in Chrome.

**Comment by mmzeeman** [comment] 2022-02-12 13:31
Maybe because of missing language files?

<img width="1328" alt="Screenshot 2022-02-12 at 14 30 28" src="https://user-images.githubusercontent.com/1024972/153713398-76e08da2-20af-4fd0-803a-75ac539fbed1.png">

**Comment by mworrell** [comment] 2022-02-12 23:12
Seems not to be related, but we should add those language files.

**Comment by mworrell** [comment] 2023-01-06 11:31
Closing for now - can't reproduce

**Closed by mworrell** 2023-01-06 11:31 UTC
Labels: javascript, unverified, admin-ui
