### ISSUE TITLE
mod_filestore

### ISSUE THREAD

**Issue by kdahmani** [zotonic/zotonic#878] opened 2014-11-27 02:21 UTC
It seems that mod_filestore does not work with S3, I then signed up for google cloud storage and that could connect without any problems, also the upload of images works fine but images still seem to be served from the local server instead.

**Comment by mworrell** [comment] 2015-02-16 21:33
Assuming the problem is solved, closing for now.

**Closed by mworrell** 2015-02-16 21:33 UTC
Labels: modules, pending reply
