### ISSUE TITLE
'relation "config" does not exist' errors

### ISSUE THREAD

**Issue by IvanMartinez** [zotonic/zotonic#699] opened 2013-12-18 10:07 UTC
I'm using Zotonic 0.9.4 with the following enviroment:

- Linux Mint 13 Maya, 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
- Erlang R16B01 (erts-5.10.2)
- PostgreSQL 9.1.11

When I recompiled Zotonic after generating the sites, I got errors like these:

20:55:16.878 [warning] blog1_com: Installing database blog1_com.public at blog1_com@127.0.0.1:5432
20:55:17.190 [info] SQL error {error,{error,error,<<"42P01">>,<<"relation "config" does not exist">>,[{position,<<"15">>}]}} : "select * from config order by module, key"
20:55:18.097 [info] SQL error {error,{error,error,<<"42P01">>,<<"relation "config" does not exist">>,[{position,<<"15">>}]}} : "select * from config order by module, key"
20:55:19.098 [info] SQL error {error,{error,error,<<"42P01">>,<<"relation "config" does not exist">>,[{position,<<"15">>}]}} : "select * from config order by module, key"
20:55:20.098 [info] SQL error {error,{error,error,<<"42P01">>,<<"relation "config" does not exist">>,[{position,<<"15">>}]}} : "select * from config order by module, key"
20:55:20.877 [info] DEBUG: z_install_data:35  {blog1_com,"Install start."}

However everything seems to work fine.

**Comment by mworrell** [comment] 2015-02-16 21:28
Can we reproduce this?

@kaos

**Comment by mworrell** [comment] 2015-04-22 14:06
Closing for now as we can't reproduce the problem.

**Closed by mworrell** 2015-04-22 14:06 UTC
