### ISSUE TITLE
[mod_authentication] Password reset causes crash on 0.x

### ISSUE THREAD

**Issue by fredpook** [zotonic/zotonic#1613] opened 2017-02-21 12:01 UTC
The password reset flow works fine, mail link and all,  up to the enter password screen.
This works ok on  0.24.1 but not on 0.x

crash log is:
```
12:56:04.960 [info] reset
enif_send: env==NULL on non-SMP VM/opt/zotonic/src/scripts/zotonic-debug: line 33:  5218 Aborted                 $ERL -env ERL_MAX_PORTS $MAX_PORTS
+P $MAX_PROCESSES +K $KERNEL_POLL -pa $PA $NAME_ARG $NODENAME@$NODEHOST -boot start_sasl $(find_config_arg erlang.config) $(find_config_arg zotonic.config) -sasl errlog_type error -s zotonic
```

**Comment by ddeboer** [comment] 2017-02-21 12:38
Related to bcrypt?

**Comment by mmzeeman** [comment] 2017-02-21 12:54
That must be the case as it is the only nif which uses enif_send.

**Comment by mmzeeman** [comment] 2017-02-21 12:59
On non-smp systems the port version should be used. See https://github.com/smarkets/erlang-bcrypt. This can be configured in erlang.config.

**Comment by ddeboer** [comment] 2017-02-22 08:36
@mmzeeman Is this mentioned in our docs? If not, we should add it.

**Comment by mmzeeman** [comment] 2017-02-22 09:51
The plan is that we want to enable the port version by default. The problem is that the bcrypt port version does not compile with rebar3. The port version can be enabled for the 0.x branch because this branch uses rebar2.

**Comment by ddeboer** [comment] 2017-02-22 09:52
Right, see also https://github.com/zotonic/zotonic/issues/1490.

**Comment by fredpook** [comment] 2017-03-15 14:38
I manually added
 {bcrypt,
    [{mechanism, port}, {pool_size, 4}]
 },
in the erlang.config
and that solved this issue for now.

Is the final solution coming in version 1.0?

**Comment by mmzeeman** [comment] 2017-03-15 16:04
Good to know it solves the problem. This will be included in 1.0. We are waiting for a fix from the bcrypt dep.

**Comment by ddeboer** [comment] 2017-08-16 11:53
@mmzeeman Zotonic now uses bcrypt from ErlangPack, in which I’ve included the [Rebar3 fix](https://github.com/erlangpack/bcrypt/commit/1b0ddea21fc5c683e37eafd552a6df83453a83ba). We should now be able to use the `mechanism` [configuration](https://github.com/erlangpack/bcrypt#configuration) to switch to `port`. Do we still want to do this by default in Zotonic?

**Comment by ddeboer** [comment] 2017-08-16 11:57
Duplicate of #1490.

**Closed by ddeboer** 2017-08-16 11:57 UTC
