### ISSUE TITLE
Start error

### ISSUE THREAD

**Issue by kaos** [zotonic/zotonic#477] opened 2012-12-12 12:48 UTC
Got a whole bunch of these after fixing a config error for a new site: 
`2012-12-12 13:46:05.291 [error] <0.9627.0> Supervisor z_site_sup had child z_notifier started with z_notifier:start_link([{enabled,true},{host,zotonic_status},{hostname,none},{dbdatabase,none},{sign_key_simple,<<>>},{...},...]) at undefined exit with reason {already_started,<0.142.0>} in context start_error
`

**Comment by mworrell** [comment] 2015-02-16 21:05
Cant reproduce. Closing for now.

**Closed by mworrell** 2015-02-16 21:05 UTC
