### ISSUE TITLE
Bug upgrading templates from 0x to 1x

### ISSUE THREAD

**Issue by abensoft-williamthome** [zotonic/zotonic#2991] opened 2022-05-27 17:36 UTC
Hi!

We are upgrading our app from Zotonic 0x to 1x.
There is in our implementation the main template and all others derive from it.
```
_base.tpl
|
|-- base1.tpl
|   |-- home.tpl
|   `-- page.tpl
|
|-- base2.tpl
|   |-- foo.tpl
|   `-- bar.tpl
|
```
We use multiple includes, extends, and block overrides.
In 0x works well, but in 1x the content of some blocks is missing.
There are two branches in our [Zotonic fork](https://github.com/Abensoft-Ltda/zotonic) comparing one site created in 0x and the other 1x. The implementation is exactly the same and reproduces the bug.

[The branch bug/0x_tpl working](https://github.com/Abensoft-Ltda/zotonic/tree/bug/0x_tpl).
![image](https://user-images.githubusercontent.com/94546997/170756902-7b695175-786f-43da-9826-4ac93acaf237.png)

[The branch bug/1x_tpl where the bug occurs](https://github.com/Abensoft-Ltda/zotonic/tree/bug/1x_tpl).
![image](https://user-images.githubusercontent.com/94546997/170749140-4ebee4cb-1822-4a00-805d-cdaf68d5109b.png)

The example site have the main HTML as `_base.tpl` wich includes `_base_head.tpl` and `_base_body.tpl`:
```html
<!DOCTYPE html>
<html lang="{{ z_language|default:"en"|escape }}" class="environment-{{ m.site.environment }}">
	{% include "_base_head.tpl" %}
	{% include "_base_body.tpl" %}
</html>
```

The `base.tpl` extends from `_base.tpl` and the `home.tpl` extends from it. The home page overrides blocks, one is `{% block content %}` from the `_base_body.tpl`. This works in 0x but fails in 1x.

Templates links:
- [0x](https://github.com/Abensoft-Ltda/zotonic/tree/bug/0x_tpl/user/sites/foo/templates)
- [1x](https://github.com/Abensoft-Ltda/zotonic/tree/bug/1x_tpl/apps_user/foo/priv/templates)

Very much appreciated receiving some feedback and a possible solution.
We are also investigating the bug.
Thanks!

**Comment by vkatsuba** [comment] 2022-05-27 18:34
Hi @abensoft-williamthome,

I suppose the good example of `Zotonic` of version `1.X` is placed at [zotonic_example](https://github.com/zotonic/zotonic_example). You can take a look and try to compare your code changes.

Regards,
--V

**Comment by vkatsuba** [comment] 2022-05-28 11:44
@abensoft-williamthome. Looks like the issue with [template_compiler](https://github.com/zotonic/template_compiler). The version `o.X` of `Zotonic` is use `erlydtl` for compiling templates. But i `1.X` is used `template_compiler`. I also noticed that if based on your example, if we remove in `apps_user/foo/priv/templates/_base.tpl` the `{% include "_base_body.tpl" %}` and then just copy/paste data from `apps_user/foo/priv/templates/_base_body.tpl` -  all will be working as expected.

<details>
  <summary><b>Updated apps_user/foo/priv/templates/_base.tpl</b>:</summary>
  
  ```html
  <!DOCTYPE html>
<html lang="{{ z_language|default:"en"|escape }}" class="environment-{{ m.site.environment }}">
	{% include "_base_head.tpl" %}


	<body class="{% block page_class %}page{% endblock %}">

		<div class="navbar navbar-inverse navbar-fixed-top">

			<div class="container">
				<div class="navbar-header">
					<a class="navbar-brand" href="/">{{ m.site.title|default:"Your Zotonic Site" }} {% if m.site.subtitle %}{% endif %}</a>
					{# <span>{{ m.site.subtitle }}</span> #}
				</div>
				{% menu id=id %}
			</div>
		</div>
		<!-- end navbar -->

		<div class="container">

			<div class="row">
				{% block content_area %}
					{% block chapeau %}{% endblock %}

					<div class="col-lg-8 col-md-8">
						{% block content %}
							<!-- The default content goes here. -->
						{% endblock %}
						{% block below_body %}
							<!--
								The block 'below_body' is used by some modules to add
								content, it MUST be present to allow those modules to
								work properly.
								Example is 'mod_survey' which adds buttons for survey pages.
							-->
						{% endblock %}
					</div>

					<div id="sidebar" class="col-lg-4 col-md-4">
						{% block sidebar %}
							{% include "_sidebar.tpl" %}
						{% endblock %}
					</div>

				{% endblock %}

			</div>

			<div class="row">
				<div class="col-lg-12 col-md-12 clearfix" id="footer">
					<div class="pull-right">
						<p class="footer-blog-title">{% include "_powered_by_zotonic.tpl" %}</p>
					</div>
					{% menu id=id menu_id='footer_menu' %}
				</div>
			</div>
		</div>

		{% include "_js_include_jquery.tpl" %}
		{% lib
			"js/modules/jstz.min.js"
			"cotonic/cotonic.js"
			"bootstrap/js/bootstrap.min.js"
			"js/apps/zotonic-wired.js"
			"js/apps/z.widgetmanager.js"
			"js/modules/livevalidation-1.3.js"
			"js/modules/z.dialog.js"
			"js/modules/jquery.loadmask.js"
		%}

		{% block _js_include_extra %}{% endblock %}

		<script type="text/javascript" nonce="{{ m.req.csp_nonce }}">
			$(function() { $.widgetManager(); });
		</script>

		{% all include "_html_body.tpl" %}

		{% script %}

		{% worker name="auth" src="js/zotonic.auth.worker.js" args=%{  auth: m.authentication.status  } %}
	</body>

</html>
  ```

</details>

So, I suppose this is a bug of [template_compiler](https://github.com/zotonic/template_compiler).

**Comment by abensoft-alvaro** [comment] 2022-05-28 12:08
Hello @vkatsuba, yes, that's the problem we found, our base templates use some {% include %} that create new {% blocks %}. It seems from our tests that template_compiler is able to find those blocks but it's unable to set the content inside them. 
We are looking at template_compiler to try and figure out what is happening. Any pointers are welcome.

**Comment by mworrell** [comment] 2022-05-29 18:28
Hi, `template_compiler` and `erlydtl` are indeed quite different beasts.

The `template_compiler` compiles all files into separate beam files. The `erlydtl` inlines all includes into a single big template and then generates a beam file from that.

Consequence is that `erlydtl` got a merged "view" of all blocks defined in all templates. Whereas `template_compiler` only "sees" the blocks as defined in the _extends_ chain of templates.

Personally I find the feature of erlydtl where you can overrule a block defined in a separate unrelated template that is included from another part of the _base_ template a bug. It can lead to unexpected behavior if blocks are (by accident) named similarly.

The block-scoping of `template_compiler` is simpler.  In your case you will need to define all the blocks that should be overruled inside the _base_ template, or at least in a template that your template is extending from.

**Comment by abensoft-alvaro** [comment] 2022-05-29 20:18
Hello @mworrell,

Yes, the compilation is way simpler on `template_compiler`, we will adapt our base templates for this new behaviour. 
Is there any other significant change on the `template_compiler` in relation to `erlydtl`?

**Comment by mworrell** [comment] 2022-05-30 06:35
There are no real other changes (tag or syntax wise).

`template_compiler` is a lot faster and will do its best to not recompile templates on language updates or module (de)activating. It does this by calculating a checksum of the parse tree and all translations, if the check sum is not changed then the compiled template is considered up to date.

On the 0.x you would see timeouts when switching modules, adding templates, or loading translations. With the 1.x and the new template compiler these timeouts are effectively gone.

**Comment by abensoft-alvaro** [comment] 2022-05-30 13:16
Hello @mworrell,

Thank you for the information! 
We got our base templates refactored and it's working now. 
We had some problems with timeouts on template compilation in a few places, I'll test if the performance with the new template_compiler is better as soon as they become reachable again.
I guess this issue can be closed.

**Closed** 2022-05-30 14:19 UTC
