### ISSUE TITLE
blog dates - bucketing and display - timezone issue

### ISSUE THREAD

**Issue by seannaswell** [zotonic/zotonic#2235] opened 2019-11-17 21:12 UTC
When setting up a new site using the blog template, then adding a new post, the Month is reported as being the previous month. 

For instance, when creating a post in November, October will show in the Archive sidebar. When clicking on October, the post made in November will be shown.

Example here: https://seannaswell.com

**Comment by mworrell** [comment] 2019-11-18 08:31
Interesting, that is probably the usual +/- 1 confusion where months are numbered from 0 and days from 1.

**Comment by mworrell** [comment] 2019-11-18 08:31
In the 0.x or master?

**Comment by seannaswell** [comment] 2019-11-18 16:27
Using master now, but saw same behavior on 0.x previously.

**Comment by mworrell** [comment] 2019-11-20 08:24
Weird, just checked and I can't seem to reproduce the problem on 0.x.
I also don't see date-handling differences between the blog skel templates in master and 0.x.

Was the post made on the first of the month?  If so then it might be a timezone thing.

**Comment by seannaswell** [comment] 2019-11-20 22:02
My VPS provider migrated from Xen to KVM yesterday, taking my site down in the process, but I was able to test locally and verify that a post created today (20-Nov) shows in the Archive sidebar as October.

Will ping the person who reported the issue on Gitter.

**Comment by mworrell** [comment] 2019-11-20 22:03
Was this with master or 0.x ?  I have been checking the 0.x code.

**Comment by seannaswell** [comment] 2019-11-20 22:04
On master.

**Comment by seannaswell** [comment] 2019-11-20 22:12
Reviewed the conversation in Gitter, nine21 also saw the issue and is using master.

**Comment by mworrell** [comment] 2019-11-21 08:55
Then it might be a master issue after all. I can check it after I merged #2199

**Comment by mworrell** [comment] 2019-11-27 15:49
Just installed a new blog skel site and I couldn't reproduce the problem (now on the 27th of november).

**Comment by seannaswell** [comment] 2019-11-28 04:54
Migrating site to new provider, so while I cannot show, I can tell. By the way, all the best with your talk...

So, updated to current master on local machine, created a new blog site using the addsite command (nice), then created a new post. Same behavior, the Archive sidebar shows new post in October.

Could it be related to the date/time or timezone setting in Postgres?

**Comment by seannaswell** [comment] 2019-12-03 18:39
Example of issue can now be seen here: https://test.seannaswell.com

The "Test Post" was made today, Archive sidebar shows November.

**Comment by mworrell** [comment] 2019-12-03 21:08
Thinking of it - I think it is indeed time zones. The routines do their bucketing in UTC and then display the months in the local timezone of the user. As you are at -something you see 2019-12-01 00:00:00 UTC as last month.

We have to decide if we want to bucket in UTC, the timezone  of the visitor, or in the configured timezone (if any). And then also use that timezone for displaying the dates.

**Comment by seannaswell** [comment] 2019-12-06 06:49
Just to be clear, [I created a new test article just now](https://test.seannaswell.com), and the Archive sidebar shows another entry was made in November.  The Archive sidebar is always a month behind. 

The funny thing is, when clicking on November, the articles added in December are shown.

**Comment by seannaswell** [comment] 2019-12-06 06:57
![Archive](https://user-images.githubusercontent.com/17067735/70302739-63e16980-17c3-11ea-8217-5af6bf7f3d8d.png)

**Comment by mworrell** [comment] 2019-12-06 08:51
That is what I suspected, the system groups all articles by date (in UTC).
Then displays the month from say 2019-12-01 00:00:00 UTC.
Which is in your timezone still 2019-11-30, so it displays November instead of the expected December.

This is easy to solve (don't convert timezone when displaying the date), more problematic is the bucketing. Question is which timezone we want to use for the grouping:

 - UTC (which all dates in the db are in, and which we use internally)
 - User's timezone (which is derived by probing the User-Agent or from the user's preferences)
 - The preferred timezone as set in the zotonic site configuration

What do you think is most logical?

**Comment by seannaswell** [comment] 2019-12-06 19:56
Ok, understand. 

Assuming the m.search query results are cached and displayed to every visitor, it seems displaying as the user's timezone would be the most logical approach. However, not converting and displaying as UTC might be easier and less error prone.

Having managed large and busy sites for the last 10 years, you are more aware of the potential drawbacks of each, but any of the above seem to be an improvement over the current conversion approach.

**Comment by seannaswell** [comment] 2020-01-03 05:27
Thinking about this again, it seems UTC is the best approach. Quite impressive you are able to pin-point the cause of issues like this...

**Comment by mworrell** [comment] 2020-01-07 16:36
I think the 2 character change in #2286 will do the trick.

**Closed** 2020-01-07 19:32 UTC
Labels: defect
