### ISSUE TITLE
Portrait video is uploaded as landscape

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#2093] opened 2019-05-31 10:04 UTC
If you upload a portrait video (from your phone for example) it gets the wrong view in the admin, landscape.

**Comment by mworrell** [comment] 2019-06-17 08:11
Looks like we do have the correct dimensions, but the (default) viewer template (or javascript) is doing something wrong with them. Looking into it.

![Screen Shot 2019-06-17 at 10 10 14](https://user-images.githubusercontent.com/38268/59588601-44a53180-90e8-11e9-93c4-a8802c5f6e2c.png)

**Comment by mworrell** [comment] 2019-06-17 08:13
BTW in the default viewer template we also have a fallback to flash, I propose that we remove that and only use the `<video>` tag.

**Comment by mworrell** [comment] 2019-06-17 08:26
In the admin the example video you sent me shows ok, just too big for my taste.

(testing on 0.x branch and with `mod_video` enabled)

The example above is a problem in the `mod_base_site` templates, and how they handle the _responsive_ wrapper classes.

**Comment by mworrell** [comment] 2019-06-17 08:33
The `video` element is supported on all browsers except IE8 https://caniuse.com/#feat=video

@DorienD and @mmzeeman can you check with your visitor stats if we can drop IE8 support (finally)? (at least for video)

**Comment by mworrell** [comment] 2019-06-17 08:35
@DorienD I can't reproduce the problem that the video is shown horizontally. What is your setup (ffmpeg and ImageMagick versions)?

**Comment by DorienD** [comment] 2019-06-18 10:05
IE8 can be dropped in my opinion.

**Comment by mworrell** [comment] 2019-06-18 10:12
@mmzeeman how much IE8 do you see with your customers?

On my most corporate site I see 20.5% IE and of that is 0.2% IE8.
IE9 accounts for 5.6% of the IE users (that is ~1% of all visitors).

We might be ready to drop all IE other than IE11?

**Comment by mmzeeman** [comment] 2019-06-18 14:19
IE8 is very low... Most of our corporate users seem to have moved from IE to FF.

**Comment by mworrell** [comment] 2019-06-19 13:13
Fixed in #2099

**Closed by mworrell** 2019-06-19 13:13 UTC
