### ISSUE TITLE
Catinclude in moreresults

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#1060] opened 2015-10-20 15:06 UTC
Hi!

We use the moreresults action to paginate through results. The strange thing however is that the moreresults does not do a catinclude. So the next loaded results have a different template. Could the moreresults do a catinclude instead of a include?

~ Dorien

**Comment by mworrell** [comment] 2015-10-20 19:37
Duplicate of #1053

**Closed by mworrell** 2015-10-20 19:37 UTC
